// Auto-generated from Byte Backlog Stack Ranked Jan_2026.xlsx
// Last updated: January 2026
// AI Recommendations added: January 2026

export interface BacklogTicket {
  id: string;
  title: string;
  description: string;
  priority: 'Critical' | 'High' | 'Medium' | 'Low';
  status: 'New' | 'In Progress' | 'Blocked' | 'Ready for Review' | 'Completed';
  category: string;
  assignee: string;
  createdDate: string;
  workItemType: string;
  state: string;
  requestor: string;
  tags: string[];
  aiRecommendation: string;
}

export const backlogTickets: BacklogTicket[] = [
  {
    "id": "21461",
    "title": "Gift Letter update request ",
    "description": "Gift Letter update request ",
    "priority": "Medium",
    "status": "Ready for Review",
    "category": "Feature",
    "assignee": "John Feldman",
    "createdDate": "2024-04-08",
    "workItemType": "Byte Request",
    "state": "Ready to Release with Clear",
    "requestor": "Lissa Park",
    "tags": [],
    "aiRecommendation": "⚠️ AGING: 21+ months old. Ready for release - include in next Wednesday deployment. Consider priority bump if still business-critical after this long."
  },
  {
    "id": "22164",
    "title": "WV Refinance loans - Net Tangible Benefit screen and form incomplete - Need Hardstop",
    "description": "WV Refinance loans - Net Tangible Benefit screen and form incomplete - Need Hardstop",
    "priority": "Medium",
    "status": "Ready for Review",
    "category": "Feature",
    "assignee": "John Feldman",
    "createdDate": "2024-04-22",
    "workItemType": "Byte Request",
    "state": "Ready to Release with Clear",
    "requestor": "Debbi Hundley",
    "tags": [],
    "aiRecommendation": "⚠️ COMPLIANCE RISK: WV regulatory hardstop pending 21+ months. Deploy immediately - potential compliance exposure."
  },
  {
    "id": "46854",
    "title": "Byte/Clear | Sales: CA-MLDS Payment Scenario Automation",
    "description": "Byte/Clear | Sales: CA-MLDS Payment Scenario Automation",
    "priority": "Medium",
    "status": "Ready for Review",
    "category": "Feature",
    "assignee": "John Feldman",
    "createdDate": "2025-02-05",
    "workItemType": "Byte Request",
    "state": "Tuesday Release",
    "requestor": "Paula Leber",
    "tags": [],
    "aiRecommendation": "✅ READY: Scheduled for Tuesday release. Verify QA sign-off complete and release notes prepared."
  },
  {
    "id": "53508",
    "title": "Byte | Risk: TRACKING - OB Concession pushback through Byte",
    "description": "Byte | Risk: TRACKING - OB Concession pushback through Byte",
    "priority": "High",
    "status": "In Progress",
    "category": "Feature",
    "assignee": "Aaron Cyr",
    "createdDate": "2025-02-14",
    "workItemType": "Byte Request",
    "state": "Projects",
    "requestor": "KMattox@cmgfi.com",
    "tags": [],
    "aiRecommendation": "📊 PROJECT: High priority, 11 months in Projects state. Request status update from Aaron. Consider breaking into smaller deliverables."
  },
  {
    "id": "56548",
    "title": "Byte/Clear | Sales/Product: Prepayment Penalty LOS Functionality - New PPP Screen",
    "description": "Byte/Clear | Sales/Product: Prepayment Penalty LOS Functionality - New PPP Screen",
    "priority": "Medium",
    "status": "In Progress",
    "category": "Feature",
    "assignee": "Renee Perrault",
    "createdDate": "2025-03-03",
    "workItemType": "Byte Request",
    "state": "In QA",
    "requestor": "Amanda Lewis",
    "tags": [],
    "aiRecommendation": "🧪 IN QA: Track QA completion. Expected release within 1-2 weeks if testing passes."
  },
  {
    "id": "58307",
    "title": "Byte | Closing: eNote & RON Eligibililty, Requested, Cancelled & Completed fields & logic",
    "description": "Byte | Closing: eNote & RON Eligibililty, Requested, Cancelled & Completed fields & logic",
    "priority": "High",
    "status": "In Progress",
    "category": "Feature",
    "assignee": "Renee Perrault",
    "createdDate": "2025-03-18",
    "workItemType": "Byte Request",
    "state": "In QA",
    "requestor": "mbaetzel@cmgfi.com",
    "tags": [],
    "aiRecommendation": "🧪 HIGH PRIORITY IN QA: eNote/RON is industry-critical. Expedite testing. Consider dedicated QA resource."
  },
  {
    "id": "60402",
    "title": "Byte/Clear | Sales/Ops: AIO Screen Refresh plus new fields",
    "description": "Byte/Clear | Sales/Ops: AIO Screen Refresh plus new fields",
    "priority": "High",
    "status": "In Progress",
    "category": "Feature",
    "assignee": "Pam Miles",
    "createdDate": "2025-04-02",
    "workItemType": "Byte Request",
    "state": "In QA",
    "requestor": "Dave Herbst",
    "tags": [],
    "aiRecommendation": "🧪 HIGH PRIORITY IN QA: Major AIO screen update. Coordinate with related AIO tickets (92240, 92908) for unified testing."
  },
  {
    "id": "61917",
    "title": "Byte | Underwriting: Add Assignment for VP Underwriting",
    "description": "Byte | Underwriting: Add Assignment for VP Underwriting",
    "priority": "Low",
    "status": "In Progress",
    "category": "Feature",
    "assignee": "Aaron Cyr",
    "createdDate": "2025-04-17",
    "workItemType": "Byte Request",
    "state": "In Dev",
    "requestor": "Colleen Schofield",
    "tags": [],
    "aiRecommendation": "👍 ON TRACK: Low priority in dev. No immediate action needed."
  },
  {
    "id": "62369",
    "title": "Byte Dev | Product: Updated needed to the logic for pop up NDPOP001",
    "description": "Byte Dev | Product: Updated needed to the logic for pop up NDPOP001",
    "priority": "Medium",
    "status": "Ready for Review",
    "category": "Feature",
    "assignee": "John Feldman",
    "createdDate": "2025-04-22",
    "workItemType": "Byte Request",
    "state": "Tuesday Release",
    "requestor": "agledhill@cmgfi.com",
    "tags": [],
    "aiRecommendation": "✅ READY: Scheduled for Tuesday release. Ensure regression testing for popup logic complete."
  },
  {
    "id": "66076",
    "title": "Byte Dev | Disclosures: DHHL Attorney doc prep fee default add - $115.18",
    "description": "Byte Dev | Disclosures: DHHL Attorney doc prep fee default add - $115.18",
    "priority": "Medium",
    "status": "In Progress",
    "category": "Feature",
    "assignee": "Aaron Cyr",
    "createdDate": "2025-05-27",
    "workItemType": "Byte Request",
    "state": "Gathering Requirements",
    "requestor": "nlindstrom@cmghomeloans.com",
    "tags": [],
    "aiRecommendation": "⏳ STALLED: 8 months gathering requirements. Schedule stakeholder meeting with nlindstrom to finalize specs."
  },
  {
    "id": "66212",
    "title": "Byte Dev | Underwriting: Need to update the 2nd Review-Exception screen in Byte to match our current Exception policy for Credit",
    "description": "Byte Dev | Underwriting: Need to update the 2nd Review-Exception screen in Byte to match our current Exception policy for Credit",
    "priority": "Medium",
    "status": "Ready for Review",
    "category": "Feature",
    "assignee": "John Feldman",
    "createdDate": "2025-05-28",
    "workItemType": "Byte Request",
    "state": "Ready for Prod",
    "requestor": "kgriffin@cmghomeloans.com",
    "tags": [],
    "aiRecommendation": "✅ DEPLOY: Ready for Prod. Include in next release. Policy alignment is time-sensitive."
  },
  {
    "id": "69749",
    "title": "Byte Dev | Underwriting / Product: Need to lock down all Chase loan products so that any buydown cannot be borrower funded. - Copy",
    "description": "Byte Dev | Underwriting / Product: Need to lock down all Chase loan products so that any buydown cannot be borrower funded. - Copy",
    "priority": "Medium",
    "status": "Ready for Review",
    "category": "Feature",
    "assignee": "Pam Miles",
    "createdDate": "2025-06-27",
    "workItemType": "Byte Request",
    "state": "Ready to Release with Clear",
    "requestor": "kgriffin@cmghomeloans.com",
    "tags": [],
    "aiRecommendation": "⚠️ INVESTOR COMPLIANCE: Chase product restriction ready. Deploy ASAP to prevent investor buyback risk."
  },
  {
    "id": "72938",
    "title": "Byte | Disclosures: USPS county consideration in search - Copy",
    "description": "Byte | Disclosures: USPS county consideration in search - Copy",
    "priority": "Medium",
    "status": "New",
    "category": "Feature",
    "assignee": "Shannon Tavalero",
    "createdDate": "2025-07-30",
    "workItemType": "Byte Request",
    "state": "MISC",
    "requestor": "nlindstrom@cmghomeloans.com",
    "tags": [],
    "aiRecommendation": "📋 TRIAGE NEEDED: 6 months in MISC state. Clarify scope with Shannon and move to proper workflow."
  },
  {
    "id": "74328",
    "title": "Byte | Operations: Interested Party Contribution Calculation for CAP - Copy",
    "description": "Byte | Operations: Interested Party Contribution Calculation for CAP - Copy",
    "priority": "Medium",
    "status": "In Progress",
    "category": "Feature",
    "assignee": "Pam Miles",
    "createdDate": "2025-08-08",
    "workItemType": "Byte Request",
    "state": "In QA",
    "requestor": "lforconi@cmgfi.com",
    "tags": [],
    "aiRecommendation": "🧪 IN QA: IPC calculation is critical for CAP program. Prioritize QA completion."
  },
  {
    "id": "75314",
    "title": "Byte Dev (Pebble) | *UPDATE SELF EMPLOYED* Processing/Underwriting: Changes to Important Dates Screen (CAP) - Copy",
    "description": "Byte Dev (Pebble) | *UPDATE SELF EMPLOYED* Processing/Underwriting: Changes to Important Dates Screen (CAP) - Copy",
    "priority": "High",
    "status": "In Progress",
    "category": "Feature",
    "assignee": "Aaron Cyr",
    "createdDate": "2025-08-14",
    "workItemType": "Byte Request",
    "state": "In QA",
    "requestor": "lforconi@cmgfi.com",
    "tags": [],
    "aiRecommendation": "🧪 HIGH PRIORITY IN QA: Self-employed processing critical for CAP. Fast-track QA validation."
  },
  {
    "id": "76214",
    "title": "Byte / Clear | Underwriting: Requesting hard stop for income on the URLA for DSCR loans - Copy",
    "description": "Byte / Clear | Underwriting: Requesting hard stop for income on the URLA for DSCR loans - Copy",
    "priority": "Medium",
    "status": "In Progress",
    "category": "Feature",
    "assignee": "John Feldman",
    "createdDate": "2025-08-25",
    "workItemType": "Byte Request",
    "state": "In Dev",
    "requestor": "kgriffin@cmghomeloans.com",
    "tags": [],
    "aiRecommendation": "👍 ON TRACK: DSCR hardstop in development. Verify alignment with investor guidelines."
  },
  {
    "id": "77249",
    "title": "Byte | Processing: header of the URLA Borrower Screen that will display the REO/ Mortgages & HELOCS. - Copy",
    "description": "Byte | Processing: header of the URLA Borrower Screen that will display the REO/ Mortgages & HELOCS. - Copy",
    "priority": "Medium",
    "status": "In Progress",
    "category": "Feature",
    "assignee": "Renee Perrault",
    "createdDate": "2025-09-04",
    "workItemType": "Byte Request",
    "state": "Gathering Requirements",
    "requestor": "rperrault@cmgfi.com/Jenn Houston",
    "tags": [],
    "aiRecommendation": "⏳ REQUIREMENTS: 4+ months gathering requirements. Schedule finalization meeting. Renee is also requestor - clarify ownership."
  },
  {
    "id": "78114",
    "title": "Byte | Processing: VOE dates do not populate in Byte, along with training material does not support? - Copy",
    "description": "Byte | Processing: VOE dates do not populate in Byte, along with training material does not support? - Copy",
    "priority": "Medium",
    "status": "Ready for Review",
    "category": "Feature",
    "assignee": "John Feldman",
    "createdDate": "2025-09-11",
    "workItemType": "Byte Request",
    "state": "Ready for Prod",
    "requestor": "csmothers@cmgfi.com",
    "tags": [],
    "aiRecommendation": "✅ DEPLOY: Ready for Prod. Also update training materials in coordination with release."
  },
  {
    "id": "78632",
    "title": "Byte / Bundle Builder | Post Closing: AUS - DU - Add Support for DU Findings in PDF Format - Copy",
    "description": "Byte / Bundle Builder | Post Closing: AUS - DU - Add Support for DU Findings in PDF Format - Copy",
    "priority": "Medium",
    "status": "New",
    "category": "Feature",
    "assignee": "Brian Carlon",
    "createdDate": "2025-09-17",
    "workItemType": "Byte Request",
    "state": "New",
    "requestor": "apaulsen@cmgfi.com",
    "tags": [],
    "aiRecommendation": "📋 NEW: Assign and begin requirements. PDF support is standard investor requirement."
  },
  {
    "id": "79086",
    "title": "Byte / CLEAR / Doc Vendor | Product / Operations: Need Assistance from Byte Team regarding upcoming CMG Bridge Loan Product - Copy",
    "description": "Byte / CLEAR / Doc Vendor | Product / Operations: Need Assistance from Byte Team regarding upcoming CMG Bridge Loan Product - Copy",
    "priority": "High",
    "status": "New",
    "category": "Feature",
    "assignee": "Renee Perrault",
    "createdDate": "2025-09-23",
    "workItemType": "Byte Request",
    "state": "MISC",
    "requestor": "claudineb@cmgfi.com",
    "tags": [],
    "aiRecommendation": "🚨 ACTION REQUIRED: High priority new product stuck in MISC 4 months. Escalate - Bridge product launch may be blocked."
  },
  {
    "id": "79335",
    "title": "Byte | App Support: Request to provide most current Email Notifications out of LOS - Copy",
    "description": "Byte | App Support: Request to provide most current Email Notifications out of LOS - Copy",
    "priority": "Medium",
    "status": "In Progress",
    "category": "Feature",
    "assignee": "Emil Garcia",
    "createdDate": "2025-09-25",
    "workItemType": "Byte Request",
    "state": "In Dev",
    "requestor": "sierram@cmgfi.com",
    "tags": [],
    "aiRecommendation": "👍 ON TRACK: Email notifications in development. Standard progress."
  },
  {
    "id": "79484",
    "title": "Byte / Clear | Sales / Ops: FNM DU for JV Solution - Copy",
    "description": "Byte / Clear | Sales / Ops: FNM DU for JV Solution - Copy",
    "priority": "Medium",
    "status": "New",
    "category": "Feature",
    "assignee": "Unassigned",
    "createdDate": "2025-09-25",
    "workItemType": "Byte Request",
    "state": "New",
    "requestor": "tcrounse@cmgfi.com",
    "tags": [],
    "aiRecommendation": "🔴 UNASSIGNED: 4 months without owner. Assign immediately - JV solution may have partnership deadlines."
  },
  {
    "id": "46847",
    "title": "Byte/Clear | Operations: Construction Approval Screen Added",
    "description": "Byte/Clear | Operations: Construction Approval Screen Added",
    "priority": "High",
    "status": "In Progress",
    "category": "Feature",
    "assignee": "Aaron Cyr",
    "createdDate": "2025-02-05",
    "workItemType": "User Story",
    "state": "BSA in Progress",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "aiRecommendation": "⚠️ LONG BSA: 11 months in BSA. High priority construction feature blocked. Escalate business decision or descope."
  },
  {
    "id": "65701",
    "title": "Byte | Clear: Secondary Pricing: Request to re-address the COC/Points increase tech side of workflow - From 25.1 Release",
    "description": "Byte | Clear: Secondary Pricing: Request to re-address the COC/Points increase tech side of workflow - From 25.1 Release",
    "priority": "Medium",
    "status": "In Progress",
    "category": "Feature",
    "assignee": "Aaron Cyr",
    "createdDate": "2025-05-23",
    "workItemType": "User Story",
    "state": "BSA in Progress",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "aiRecommendation": "⚠️ PRICING WORKFLOW: 8 months in BSA. COC/Points impacts revenue. Prioritize business requirements finalization."
  },
  {
    "id": "72957",
    "title": "Byte | Ops / Disclosures: Open Section A \"Application Fee\" Line item for editable access by a Disclosure Coordinator persona",
    "description": "Byte | Ops / Disclosures: Open Section A \"Application Fee\" Line item for editable access by a Disclosure Coordinator persona",
    "priority": "Medium",
    "status": "New",
    "category": "Feature",
    "assignee": "Aaron Cyr",
    "createdDate": "2025-07-30",
    "workItemType": "User Story",
    "state": "Prioritized Backlog",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "aiRecommendation": "📋 BACKLOG: Aaron has heavy workload. Consider reassignment or sprint planning."
  },
  {
    "id": "73860",
    "title": "Byte | Closing and Operations: Restrict Access to Clear PTD Conditions for Closers",
    "description": "Byte | Closing and Operations: Restrict Access to Clear PTD Conditions for Closers",
    "priority": "High",
    "status": "New",
    "category": "Feature",
    "assignee": "Unassigned",
    "createdDate": "2025-08-06",
    "workItemType": "User Story",
    "state": "Prioritized Backlog",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "aiRecommendation": "🔴 UNASSIGNED HIGH: Access control is security-sensitive. Assign owner immediately and prioritize."
  },
  {
    "id": "74085",
    "title": "Byte / ComplianceEase | Disclosures / Closing: ComplianceAnalyzer BytePro Updates",
    "description": "Byte / ComplianceEase | Disclosures / Closing: ComplianceAnalyzer BytePro Updates",
    "priority": "Low",
    "status": "New",
    "category": "Feature",
    "assignee": "Kelly Mattox",
    "createdDate": "2025-08-07",
    "workItemType": "User Story",
    "state": "Prioritized Backlog",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "aiRecommendation": "📋 COMPLIANCE: Low priority but compliance-related. Monitor for regulatory deadline changes."
  },
  {
    "id": "74762",
    "title": "Automation / BYTE / Docs Vendor | Servicing: Late Charges and NSFs",
    "description": "Automation / BYTE / Docs Vendor | Servicing: Late Charges and NSFs",
    "priority": "Medium",
    "status": "New",
    "category": "Feature",
    "assignee": "Unassigned",
    "createdDate": "2025-08-12",
    "workItemType": "User Story",
    "state": "Prioritized Backlog",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "aiRecommendation": "🔴 UNASSIGNED: Servicing automation without owner 5 months. Assign to servicing-focused developer."
  },
  {
    "id": "76231",
    "title": "Byte / SmartFees | Disclosures and Operations: NY Mortgage Tax Stamps Fee Mapping - Copy",
    "description": "Byte / SmartFees | Disclosures and Operations: NY Mortgage Tax Stamps Fee Mapping - Copy",
    "priority": "High",
    "status": "In Progress",
    "category": "Feature",
    "assignee": "Aaron Cyr",
    "createdDate": "2025-08-25",
    "workItemType": "User Story",
    "state": "BSA in Progress",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "aiRecommendation": "⚠️ STATE COMPLIANCE: NY tax stamps is regulatory. 5 months in BSA - expedite requirements to avoid compliance gap."
  },
  {
    "id": "77598",
    "title": "Byte / Clear | Disclosures: COC pipeline issue received from disclosure coordinator/team lead, Ticket # 634135",
    "description": "Byte / Clear | Disclosures: COC pipeline issue received from disclosure coordinator/team lead, Ticket # 634135",
    "priority": "Low",
    "status": "New",
    "category": "Feature",
    "assignee": "Aaron Cyr",
    "createdDate": "2025-09-08",
    "workItemType": "User Story",
    "state": "Prioritized Backlog",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "aiRecommendation": "📋 PIPELINE: Review original ticket #634135 for context. May be related to COC workflow item 65701."
  },
  {
    "id": "78426",
    "title": "Byte | Product / Closing / Post Closing: Non-HFA DPA Programs - Auto-Populate Data into Funding Screen",
    "description": "Byte | Product / Closing / Post Closing: Non-HFA DPA Programs - Auto-Populate Data into Funding Screen",
    "priority": "Low",
    "status": "In Progress",
    "category": "Feature",
    "assignee": "Renee Perrault",
    "createdDate": "2025-09-15",
    "workItemType": "User Story",
    "state": "On Hold",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "aiRecommendation": "⏸️ ON HOLD: Document hold reason. DPA programs may have funding partner deadlines."
  },
  {
    "id": "78573",
    "title": "Byte | Corp Credit / Ops: Credit Vendor updates - Request to add mortgage only",
    "description": "Byte | Corp Credit / Ops: Credit Vendor updates - Request to add mortgage only",
    "priority": "Medium",
    "status": "In Progress",
    "category": "Feature",
    "assignee": "Shannon Tavalero",
    "createdDate": "2025-09-17",
    "workItemType": "User Story",
    "state": "BSA in Progress",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "aiRecommendation": "⏳ BSA: Credit vendor integration 4 months in BSA. Verify vendor API timeline alignment."
  },
  {
    "id": "78671",
    "title": "Byte | Ops Post Closing: Conditions",
    "description": "Byte | Ops Post Closing: Conditions",
    "priority": "High",
    "status": "New",
    "category": "Feature",
    "assignee": "Unassigned",
    "createdDate": "2025-09-18",
    "workItemType": "User Story",
    "state": "Prioritized Backlog",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "aiRecommendation": "🔴 UNASSIGNED HIGH: Post closing conditions critical for investor delivery. Assign and begin requirements ASAP."
  },
  {
    "id": "78917",
    "title": "Doc | Disclosures: URGENT LE DELIVERY DATE ISSUE",
    "description": "Doc | Disclosures: URGENT LE DELIVERY DATE ISSUE",
    "priority": "Low",
    "status": "New",
    "category": "Feature",
    "assignee": "Kelly Mattox",
    "createdDate": "2025-09-22",
    "workItemType": "User Story",
    "state": "Prioritized Backlog",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "aiRecommendation": "⚠️ PRIORITY MISMATCH: Title says URGENT but priority is Low. Review and adjust priority if still urgent."
  },
  {
    "id": "81479",
    "title": "Byte | Ops / Processing: Prepayment Penalty override",
    "description": "Byte | Ops / Processing: Prepayment Penalty override",
    "priority": "High",
    "status": "In Progress",
    "category": "Feature",
    "assignee": "Renee Perrault",
    "createdDate": "2025-10-13",
    "workItemType": "User Story",
    "state": "On Hold",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "aiRecommendation": "⏸️ HIGH ON HOLD: PPP override is high priority but blocked. Escalate - document blocker and timeline to resume."
  },
  {
    "id": "81505",
    "title": "Byte | Ops / Closing: SDHFA Fee Mapping Issue",
    "description": "Byte | Ops / Closing: SDHFA Fee Mapping Issue",
    "priority": "High",
    "status": "In Progress",
    "category": "Feature",
    "assignee": "Aaron Cyr",
    "createdDate": "2025-10-13",
    "workItemType": "User Story",
    "state": "BSA in Progress",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "aiRecommendation": "⚠️ HFA PROGRAM: State HFA fee mapping affects affordable lending. Push for requirements completion."
  },
  {
    "id": "81508",
    "title": "Byte / Doc Vendor | Ops / Closing: Title Premium Adjustment Hardcode (BYTE PRO Build)",
    "description": "Byte / Doc Vendor | Ops / Closing: Title Premium Adjustment Hardcode (BYTE PRO Build)",
    "priority": "Low",
    "status": "In Progress",
    "category": "Feature",
    "assignee": "Unassigned",
    "createdDate": "2025-10-13",
    "workItemType": "User Story",
    "state": "On Hold",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "aiRecommendation": "⏸️ UNASSIGNED + ON HOLD: Needs owner before hold can be resolved. Assign or close if no longer needed."
  },
  {
    "id": "81528",
    "title": "Byte / ValueLink | Ops / Closing: ValueLink Parcel ID Pushback",
    "description": "Byte / ValueLink | Ops / Closing: ValueLink Parcel ID Pushback",
    "priority": "Medium",
    "status": "New",
    "category": "Feature",
    "assignee": "Pam Miles",
    "createdDate": "2025-10-14",
    "workItemType": "User Story",
    "state": "Prioritized Backlog",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "aiRecommendation": "📋 INTEGRATION: ValueLink integration item. Coordinate with vendor on API availability."
  },
  {
    "id": "81621",
    "title": "Byte / Clear Docs | Sales: Daily Summary for activity in the loan (SC notes)",
    "description": "Byte / Clear Docs | Sales: Daily Summary for activity in the loan (SC notes)",
    "priority": "Low",
    "status": "New",
    "category": "Feature",
    "assignee": "Unassigned",
    "createdDate": "2025-10-14",
    "workItemType": "User Story",
    "state": "Prioritized Backlog",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "aiRecommendation": "📋 LOW: Nice-to-have feature. Keep in backlog until higher priorities addressed."
  },
  {
    "id": "81789",
    "title": "Byte / Clear | Product / Bank: Bank CMG - Wholesale Channel Setup - Copy for BYTE platform",
    "description": "Byte / Clear | Product / Bank: Bank CMG - Wholesale Channel Setup - Copy for BYTE platform",
    "priority": "High",
    "status": "In Progress",
    "category": "Feature",
    "assignee": "Kelly Mattox",
    "createdDate": "2025-10-15",
    "workItemType": "User Story",
    "state": "BSA in Progress",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "aiRecommendation": "🏦 STRATEGIC: Bank wholesale channel is major initiative. Track closely - coordinate with bank partnership team."
  },
  {
    "id": "84372",
    "title": "EX | Byte / Doc Vendor | Sales / Servicing / Ops / Compliance: Assumption Loans in Byte and Docs",
    "description": "EX | Byte / Doc Vendor | Sales / Servicing / Ops / Compliance: Assumption Loans in Byte and Docs",
    "priority": "Medium",
    "status": "New",
    "category": "Feature",
    "assignee": "Renee Perrault",
    "createdDate": "2025-10-20",
    "workItemType": "User Story",
    "state": "Prioritized Backlog",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "aiRecommendation": "📈 MARKET TREND: Assumption loans increasing in high-rate environment. Consider priority bump."
  },
  {
    "id": "85172",
    "title": "EX | Byte / Marketing Apps | Sales / Borrower / Compliance: Borrower Opt Out Trigger for privacy notice",
    "description": "EX | Byte / Marketing Apps | Sales / Borrower / Compliance: Borrower Opt Out Trigger for privacy notice",
    "priority": "High",
    "status": "In Progress",
    "category": "Feature",
    "assignee": "Renee Perrault",
    "createdDate": "2025-10-22",
    "workItemType": "User Story",
    "state": "BSA in Progress",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "aiRecommendation": "⚠️ PRIVACY COMPLIANCE: Borrower opt-out is regulatory requirement. Expedite BSA - potential CCPA/GLBA exposure."
  },
  {
    "id": "85773",
    "title": "Byte | Ops / Underwriting: Document Redisplay for Expiration Dates",
    "description": "Byte | Ops / Underwriting: Document Redisplay for Expiration Dates",
    "priority": "Medium",
    "status": "New",
    "category": "Feature",
    "assignee": "Renee Perrault",
    "createdDate": "2025-10-29",
    "workItemType": "User Story",
    "state": "Prioritized Backlog",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "aiRecommendation": "📋 UX: Document expiration visibility improves ops efficiency. Schedule when Renee's workload allows."
  },
  {
    "id": "85961",
    "title": "Byte | Qc / Risk: QC cannot access files when UW is in the file (Byte)",
    "description": "Byte | Qc / Risk: QC cannot access files when UW is in the file (Byte)",
    "priority": "Medium",
    "status": "New",
    "category": "Feature",
    "assignee": "Renee Perrault",
    "createdDate": "2025-10-30",
    "workItemType": "User Story",
    "state": "Prioritized Backlog",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "aiRecommendation": "🔒 ACCESS CONFLICT: File locking issue impacts QC workflow. May need architecture review."
  },
  {
    "id": "86014",
    "title": "Byte / Doc Vendor | Product / Credit: FHA ARM – Byte Not Updating First Rate Payment Date Correctly",
    "description": "Byte / Doc Vendor | Product / Credit: FHA ARM – Byte Not Updating First Rate Payment Date Correctly",
    "priority": "Medium",
    "status": "In Progress",
    "category": "Feature",
    "assignee": "Renee Perrault",
    "createdDate": "2025-10-31",
    "workItemType": "User Story",
    "state": "On Hold",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "aiRecommendation": "⏸️ FHA COMPLIANCE: FHA ARM calculation error on hold. Document blocker - FHA audits check this."
  },
  {
    "id": "86228",
    "title": "Byte / Clear | Sales / Product / Secondary: .5-1 Buydown Option",
    "description": "Byte / Clear | Sales / Product / Secondary: .5-1 Buydown Option",
    "priority": "Low",
    "status": "New",
    "category": "Feature",
    "assignee": "Renee Perrault",
    "createdDate": "2025-11-04",
    "workItemType": "User Story",
    "state": "Prioritized Backlog",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "aiRecommendation": "📋 PRODUCT: New buydown option. Low priority - schedule when resources available."
  },
  {
    "id": "87116",
    "title": "Byte / Docs | Post Closing / Ops / Underwriting: Updating URLA data in Byte",
    "description": "Byte / Docs | Post Closing / Ops / Underwriting: Updating URLA data in Byte",
    "priority": "Medium",
    "status": "New",
    "category": "Feature",
    "assignee": "Renee Perrault",
    "createdDate": "2025-11-13",
    "workItemType": "User Story",
    "state": "Prioritized Backlog",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "aiRecommendation": "📋 URLA: Data update feature. Standard priority - schedule when Renee's backlog clears."
  },
  {
    "id": "87757",
    "title": "Automation / Byte | Ops / Processing / Servicing: Lereta flood integration - Bytepro 26.1",
    "description": "Automation / Byte | Ops / Processing / Servicing: Lereta flood integration - Bytepro 26.1",
    "priority": "Medium",
    "status": "In Progress",
    "category": "Feature",
    "assignee": "Kelly Mattox",
    "createdDate": "2025-11-19",
    "workItemType": "User Story",
    "state": "On Hold",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "aiRecommendation": "⏸️ BYTEPRO 26.1: Dependent on BytePro release. Track vendor timeline and coordinate."
  },
  {
    "id": "87799",
    "title": "Byte | Wholesale Sales: Update - Please send to Sharon Tavalero",
    "description": "Byte | Wholesale Sales: Update - Please send to Sharon Tavalero",
    "priority": "High",
    "status": "New",
    "category": "Feature",
    "assignee": "Shannon Tavalero",
    "createdDate": "2025-11-19",
    "workItemType": "User Story",
    "state": "Prioritized Backlog",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "aiRecommendation": "🚨 VAGUE TITLE: High priority but unclear scope. Clarify requirements with Shannon immediately."
  },
  {
    "id": "87832",
    "title": "Byte / Clear | Sales / Ops / Disclosures: Lender Paid Comp populating as Discount Points",
    "description": "Byte / Clear | Sales / Ops / Disclosures: Lender Paid Comp populating as Discount Points",
    "priority": "Medium",
    "status": "New",
    "category": "Feature",
    "assignee": "Aaron Cyr",
    "createdDate": "2025-11-19",
    "workItemType": "User Story",
    "state": "Prioritized Backlog",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "aiRecommendation": "⚠️ DISCLOSURE ERROR: Comp/Points confusion is TRID violation risk. Consider priority increase."
  },
  {
    "id": "89297",
    "title": "Byte | Ops / Processing: Hardstop for delegated MI when non-delegated is required.",
    "description": "Byte | Ops / Processing: Hardstop for delegated MI when non-delegated is required.",
    "priority": "High",
    "status": "New",
    "category": "Feature",
    "assignee": "Aaron Cyr",
    "createdDate": "2025-12-01",
    "workItemType": "User Story",
    "state": "Prioritized Backlog",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "aiRecommendation": "🚨 MI COMPLIANCE: Delegated vs non-delegated MI is investor requirement. High priority - begin immediately."
  },
  {
    "id": "89300",
    "title": "Byte | Ops / Underwriting / Processing: Prior to Purchase Hardstop",
    "description": "Byte | Ops / Underwriting / Processing: Prior to Purchase Hardstop",
    "priority": "Medium",
    "status": "In Progress",
    "category": "Feature",
    "assignee": "Renee Perrault",
    "createdDate": "2025-12-01",
    "workItemType": "User Story",
    "state": "On Hold",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "aiRecommendation": "⏸️ ON HOLD: Prior to purchase hardstop blocked. Document reason and target resume date."
  },
  {
    "id": "89333",
    "title": "Byte | Ops / Closing: Wiring Instructions Confirmation Date Macro to remove date after 7 business days & mirror the date on other Byte screens",
    "description": "Byte | Ops / Closing: Wiring Instructions Confirmation Date Macro to remove date after 7 business days & mirror the date on other Byte screens",
    "priority": "Medium",
    "status": "New",
    "category": "Feature",
    "assignee": "Renee Perrault",
    "createdDate": "2025-12-01",
    "workItemType": "User Story",
    "state": "Prioritized Backlog",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "aiRecommendation": "🔒 FRAUD PREVENTION: Wire instruction expiration is security control. Prioritize for risk mitigation."
  },
  {
    "id": "89658",
    "title": "BYTE / Clear | Sales: credit report after file submission - Copy",
    "description": "BYTE / Clear | Sales: credit report after file submission - Copy",
    "priority": "Low",
    "status": "New",
    "category": "Feature",
    "assignee": "Unassigned",
    "createdDate": "2025-12-04",
    "workItemType": "User Story",
    "state": "Prioritized Backlog",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "aiRecommendation": "📋 UNASSIGNED: Low priority but needs owner. Assign when team capacity allows."
  },
  {
    "id": "89718",
    "title": "Byte | Disclosures: Correct AIO fees for Franklin, TN branch when property is in NC.",
    "description": "Byte | Disclosures: Correct AIO fees for Franklin, TN branch when property is in NC.",
    "priority": "High",
    "status": "Ready for Review",
    "category": "Feature",
    "assignee": "Aaron Cyr",
    "createdDate": "2025-12-05",
    "workItemType": "User Story",
    "state": "Ready for Grooming",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "aiRecommendation": "📋 GROOMING: Ready for grooming. Schedule for next sprint planning. Fee correction prevents disclosure errors."
  },
  {
    "id": "89961",
    "title": "Byte | Secondary / Pricing: HELOC and 1st Lien Types",
    "description": "Byte | Secondary / Pricing: HELOC and 1st Lien Types",
    "priority": "Medium",
    "status": "In Progress",
    "category": "Feature",
    "assignee": "Kelly Mattox",
    "createdDate": "2025-12-09",
    "workItemType": "User Story",
    "state": "On Hold",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "aiRecommendation": "⏸️ PRICING: HELOC pricing on hold. Document blocker - HELOC product expansion may be waiting."
  },
  {
    "id": "89991",
    "title": "Doc Vendor | Ops / Closing: FHA Lead Base Paint Auto Condition.",
    "description": "Doc Vendor | Ops / Closing: FHA Lead Base Paint Auto Condition.",
    "priority": "Low",
    "status": "In Progress",
    "category": "Feature",
    "assignee": "Renee Perrault",
    "createdDate": "2025-12-09",
    "workItemType": "User Story",
    "state": "BSA in Progress",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "aiRecommendation": "📋 FHA CONDITION: Lead paint condition automation. Low priority but FHA compliance related."
  },
  {
    "id": "90323",
    "title": "BYTE / Clear 1 | Sales: WHL Change of circumstance automation",
    "description": "BYTE / Clear 1 | Sales: WHL Change of circumstance automation",
    "priority": "Medium",
    "status": "New",
    "category": "Feature",
    "assignee": "Kelly Mattox",
    "createdDate": "2025-12-14",
    "workItemType": "User Story",
    "state": "Prioritized Backlog",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "aiRecommendation": "📋 WHOLESALE: COC automation for wholesale channel. Coordinate with wholesale team for requirements."
  },
  {
    "id": "90878",
    "title": "BYTE / Clear | Ops Underwriting: Income Calc ID from Fannie Mae Income Calculator needs to be entered into Byte/DU",
    "description": "BYTE / Clear | Ops Underwriting: Income Calc ID from Fannie Mae Income Calculator needs to be entered into Byte/DU",
    "priority": "Medium",
    "status": "In Progress",
    "category": "Feature",
    "assignee": "Shannon Tavalero",
    "createdDate": "2025-12-17",
    "workItemType": "User Story",
    "state": "BSA in Progress",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "aiRecommendation": "📊 GSE INTEGRATION: Fannie Mae Income Calc ID integration. Verify field mapping with GSE specs."
  },
  {
    "id": "90970",
    "title": "BYTE | Servicing / Product: - Simple Interest field (Byte Program Defaults) (Project)",
    "description": "BYTE | Servicing / Product: - Simple Interest field (Byte Program Defaults) (Project)",
    "priority": "Medium",
    "status": "New",
    "category": "Feature",
    "assignee": "Unassigned",
    "createdDate": "2025-12-18",
    "workItemType": "User Story",
    "state": "Prioritized Backlog",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "aiRecommendation": "🔴 UNASSIGNED: Servicing field needs owner. Simple interest affects payment calculations."
  },
  {
    "id": "90972",
    "title": "BYTE | Compliance: New York Byte Hardstop Updates",
    "description": "BYTE | Compliance: New York Byte Hardstop Updates",
    "priority": "High",
    "status": "In Progress",
    "category": "Feature",
    "assignee": "Renee Perrault",
    "createdDate": "2025-12-18",
    "workItemType": "User Story",
    "state": "On Hold",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "aiRecommendation": "🚨 STATE COMPLIANCE ON HOLD: NY compliance updates blocked. HIGH RISK - NY has strict enforcement. Escalate immediately."
  },
  {
    "id": "90979",
    "title": "BYTE | Ops: PTR Condition Stage Hard stop",
    "description": "BYTE | Ops: PTR Condition Stage Hard stop",
    "priority": "High",
    "status": "In Progress",
    "category": "Feature",
    "assignee": "Renee Perrault",
    "createdDate": "2025-12-18",
    "workItemType": "User Story",
    "state": "BSA in Progress",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "aiRecommendation": "⏳ BSA: PTR hardstop in requirements. Push for completion - affects loan processing flow."
  },
  {
    "id": "91226",
    "title": "Byte | Ops / Closing / Post Closing: Form H8 and H9 - Hardstop",
    "description": "Byte | Ops / Closing / Post Closing: Form H8 and H9 - Hardstop",
    "priority": "Medium",
    "status": "In Progress",
    "category": "Feature",
    "assignee": "Renee Perrault",
    "createdDate": "2025-12-23",
    "workItemType": "User Story",
    "state": "BSA in Progress",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "aiRecommendation": "📋 FORMS: H8/H9 form hardstop. Standard compliance item - continue BSA process."
  },
  {
    "id": "91254",
    "title": "Byte / Doc Vendor | Compliance / Servicing / Post Closing: Bond First Payment Letters",
    "description": "Byte / Doc Vendor | Compliance / Servicing / Post Closing: Bond First Payment Letters",
    "priority": "High",
    "status": "In Progress",
    "category": "Feature",
    "assignee": "Renee Perrault",
    "createdDate": "2025-12-23",
    "workItemType": "User Story",
    "state": "On Hold",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "aiRecommendation": "⏸️ BOND COMPLIANCE: First payment letters on hold. Bond programs have investor requirements - verify hold reason."
  },
  {
    "id": "91364",
    "title": "Docutech | Servicing | First Payment Letter Address Byte Macro Logic Updates - Copy",
    "description": "Docutech | Servicing | First Payment Letter Address Byte Macro Logic Updates - Copy",
    "priority": "High",
    "status": "In Progress",
    "category": "Feature",
    "assignee": "Renee Perrault",
    "createdDate": "2025-12-24",
    "workItemType": "User Story",
    "state": "On Hold",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "aiRecommendation": "⏸️ RELATED: May be related to 91254. Consider combining or sequencing these items."
  },
  {
    "id": "91652",
    "title": "Byte | Ops Closing / Funding: Section G Fee Review",
    "description": "Byte | Ops Closing / Funding: Section G Fee Review",
    "priority": "High",
    "status": "New",
    "category": "Feature",
    "assignee": "Aaron Cyr",
    "createdDate": "2025-12-30",
    "workItemType": "User Story",
    "state": "Prioritized Backlog",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "aiRecommendation": "🚨 FEE COMPLIANCE: Section G fee review is TRID-critical. Begin requirements immediately - disclosure accuracy required."
  },
  {
    "id": "92002",
    "title": "Byte / Clear | Project: New AMC - Great South Bay Appraisal Management Company - Add to Byte/Clear",
    "description": "Byte / Clear | Project: New AMC - Great South Bay Appraisal Management Company - Add to Byte/Clear",
    "priority": "High",
    "status": "In Progress",
    "category": "Feature",
    "assignee": "Aaron Cyr",
    "createdDate": "2026-01-06",
    "workItemType": "User Story",
    "state": "On Hold",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "aiRecommendation": "⏸️ VENDOR: New AMC integration on hold. May have contract/timeline with vendor - verify business status."
  },
  {
    "id": "92233",
    "title": "Byte | Ops / Underwriting: Need a new status dropdown on the conditions",
    "description": "Byte | Ops / Underwriting: Need a new status dropdown on the conditions",
    "priority": "High",
    "status": "In Progress",
    "category": "Feature",
    "assignee": "Renee Perrault",
    "createdDate": "2026-01-07",
    "workItemType": "User Story",
    "state": "On Hold",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "aiRecommendation": "⏸️ UX: Conditions dropdown on hold. Document blocker - may be waiting on business decision."
  },
  {
    "id": "92240",
    "title": "Byte | AIO / Sales / Product: new default rule and new hard-stop rule to the AIO screen, specifically the Eligible Program & Servicer Preference section",
    "description": "Byte | AIO / Sales / Product: new default rule and new hard-stop rule to the AIO screen, specifically the Eligible Program & Servicer Preference section",
    "priority": "Medium",
    "status": "New",
    "category": "Feature",
    "assignee": "Aaron Cyr",
    "createdDate": "2026-01-07",
    "workItemType": "User Story",
    "state": "Prioritized Backlog",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "aiRecommendation": "🔗 RELATED: Coordinate with AIO screen items 60402 and 92908 for unified implementation."
  },
  {
    "id": "92360",
    "title": "BYTE | Ops Closing: Credit Verifications Bundle Fee",
    "description": "BYTE | Ops Closing: Credit Verifications Bundle Fee",
    "priority": "Medium",
    "status": "Completed",
    "category": "Feature",
    "assignee": "Kelly Mattox",
    "createdDate": "2026-01-09",
    "workItemType": "User Story",
    "state": "Released",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "aiRecommendation": "✅ RELEASED: Successfully deployed. No action needed."
  },
  {
    "id": "92379",
    "title": "BYTE | Ops Closing: Fee Lines for Settle In Program to flow to section H of CD",
    "description": "BYTE | Ops Closing: Fee Lines for Settle In Program to flow to section H of CD",
    "priority": "Medium",
    "status": "New",
    "category": "Feature",
    "assignee": "Renee Perrault",
    "createdDate": "2026-01-09",
    "workItemType": "User Story",
    "state": "Prioritized Backlog",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "aiRecommendation": "📋 CD MAPPING: Settle In program fee flow. Schedule for requirements when Renee available."
  },
  {
    "id": "92476",
    "title": "Byte | Post Closing / Ops: Redisplay of Warehouse Bank Cardex Fields into new fields in Warehouse Info Screen",
    "description": "Byte | Post Closing / Ops: Redisplay of Warehouse Bank Cardex Fields into new fields in Warehouse Info Screen",
    "priority": "Medium",
    "status": "New",
    "category": "Feature",
    "assignee": "Renee Perrault",
    "createdDate": "2026-01-11",
    "workItemType": "User Story",
    "state": "Prioritized Backlog",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "aiRecommendation": "📋 WAREHOUSE: Field redisplay for warehouse operations. Medium priority - schedule accordingly."
  },
  {
    "id": "92486",
    "title": "Byte | Disclosures / Compliance: Reset Compliance Ease Password prior to 2/10/26",
    "description": "Byte | Disclosures / Compliance: Reset Compliance Ease Password prior to 2/10/26",
    "priority": "High",
    "status": "New",
    "category": "Feature",
    "assignee": "Kelly Mattox",
    "createdDate": "2026-01-12",
    "workItemType": "User Story",
    "state": "New",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "aiRecommendation": "🚨🚨 DEADLINE 2/10/26: ComplianceEase password reset required in <3 weeks. IMMEDIATE ACTION - system access at risk."
  },
  {
    "id": "92632",
    "title": "Byte / Clear | Sales: CCW: Need to multiply Credit Verifications Bundle by # of applications",
    "description": "Byte / Clear | Sales: CCW: Need to multiply Credit Verifications Bundle by # of applications",
    "priority": "Critical",
    "status": "New",
    "category": "Feature",
    "assignee": "Aaron Cyr",
    "createdDate": "2026-01-12",
    "workItemType": "User Story",
    "state": "Prioritized Backlog",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "aiRecommendation": "🚨🚨🚨 CRITICAL: Only Critical priority item. Credit verification fee calculation error. BEGIN IMMEDIATELY - affects revenue and disclosure accuracy."
  },
  {
    "id": "92908",
    "title": "Byte | AIO / Product: Add new AIO Screen Field, and corresponding default rule and hard stop",
    "description": "Byte | AIO / Product: Add new AIO Screen Field, and corresponding default rule and hard stop",
    "priority": "High",
    "status": "New",
    "category": "Feature",
    "assignee": "Aaron Cyr",
    "createdDate": "2026-01-15",
    "workItemType": "User Story",
    "state": "Prioritized Backlog",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "aiRecommendation": "🔗 RELATED: Third AIO screen item. Coordinate with 60402 and 92240 for batch implementation."
  },
  {
    "id": "93001",
    "title": "Byte | Ops Underwriting: Comprehensive list of AIO hardstops and defaults put into Byte and CLEAR",
    "description": "Byte | Ops Underwriting: Comprehensive list of AIO hardstops and defaults put into Byte and CLEAR",
    "priority": "Medium",
    "status": "In Progress",
    "category": "Feature",
    "assignee": "Renee Perrault",
    "createdDate": "2026-01-16",
    "workItemType": "User Story",
    "state": "BSA in Progress",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "aiRecommendation": "📋 AIO MASTER: This may supersede other AIO items. Verify scope overlap with 60402, 92240, 92908."
  },
  {
    "id": "93150",
    "title": "Byte | Sales / Ops: Essent MI Integration - 401 Unauthorized Errors for 3+ Months",
    "description": "Byte | Sales / Ops: Essent MI Integration - 401 Unauthorized Errors for 3+ Months",
    "priority": "Medium",
    "status": "New",
    "category": "Feature",
    "assignee": "Kelly Mattox",
    "createdDate": "2026-01-20",
    "workItemType": "User Story",
    "state": "New",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "aiRecommendation": "🔥 INTEGRATION BROKEN: Essent MI 401 errors for 3+ months = broken integration. ESCALATE - users manually handling MI. Consider priority bump to High."
  }
];
