// Auto-generated from Copy of Byte Backlog Stack Ranked Jan_2026 _ LF Draft (1).xlsx
// Last updated: January 30, 2026
// Stack ranked by Lauren Forconi & Kelly Mattox (final review)
// 57 items ordered 1-57 after removing completed/released items

export interface BacklogTicket {
  id: string;
  title: string;
  description: string;
  priority: 'High' | 'Medium' | 'Low';
  priorityLevel: string;
  stackRank: number;
  status: 'New' | 'In Progress' | 'Blocked' | 'Ready for Review' | 'Completed';
  category: string;
  assignee: string;
  createdDate: string;
  workItemType: string;
  state: string;
  requestor: string;
  tags: string[];
  explanation: string;
}

export const backlogTickets: BacklogTicket[] = [
  // ========================================
  // 2 - HIGH (Stack Rank 1+)
  // ========================================
  {
    "id": "92486",
    "title": "Byte | Disclosures / Compliance: Reset Compliance Ease Password prior to 2/10/26",
    "description": "Byte | Disclosures / Compliance: Reset Compliance Ease Password prior to 2/10/26",
    "priority": "High",
    "priorityLevel": "2 - High",
    "stackRank": 1,
    "status": "New",
    "category": "Feature",
    "assignee": "Kelly Mattox",
    "createdDate": "2026-01-12",
    "workItemType": "User Story",
    "state": "New",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "explanation": "Required completion date of 2/10"
  },
  {
    "id": "90979",
    "title": "BYTE | Ops: PTR Condition Stage Hard stop",
    "description": "BYTE | Ops: PTR Condition Stage Hard stop",
    "priority": "High",
    "priorityLevel": "2 - High",
    "stackRank": 2,
    "status": "In Progress",
    "category": "Feature",
    "assignee": "Renee Perrault",
    "createdDate": "2025-12-18",
    "workItemType": "User Story",
    "state": "BSA in Progress",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "explanation": "Waiting for Ops"
  },
  {
    "id": "73860",
    "title": "Byte | Closing and Operations: Restrict Access to Clear PTD Conditions for Closers",
    "description": "Byte | Closing and Operations: Restrict Access to Clear PTD Conditions for Closers",
    "priority": "High",
    "priorityLevel": "2 - High",
    "stackRank": 3,
    "status": "New",
    "category": "Feature",
    "assignee": "Unassigned",
    "createdDate": "2025-08-06",
    "workItemType": "User Story",
    "state": "Prioritized Backlog",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "explanation": "Part of Conditions Screen Relabelling Project"
  },
  {
    "id": "92002",
    "title": "Byte / Clear | Project: New AMC - Great South Bay Appraisal Management Company - Add to Byte/Clear",
    "description": "Byte / Clear | Project: New AMC - Great South Bay Appraisal Management Company - Add to Byte/Clear",
    "priority": "High",
    "priorityLevel": "2 - High",
    "stackRank": 4,
    "status": "Blocked",
    "category": "Feature",
    "assignee": "Aaron Cyr",
    "createdDate": "2026-01-06",
    "workItemType": "User Story",
    "state": "On Hold",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "explanation": "On Hold for Clear Parity"
  },
  {
    "id": "53508",
    "title": "Byte | Risk: TRACKING - OB Concession pushback through Byte",
    "description": "Byte | Risk: TRACKING - OB Concession pushback through Byte",
    "priority": "High",
    "priorityLevel": "2 - High",
    "stackRank": 5,
    "status": "In Progress",
    "category": "Feature",
    "assignee": "Aaron Cyr",
    "createdDate": "2025-02-14",
    "workItemType": "Byte Request",
    "state": "BSA in Progress",
    "requestor": "KMattox@cmgfi.com",
    "tags": [],
    "explanation": ""
  },
  {
    "id": "60402",
    "title": "Byte/Clear | Sales/Ops: AIO Screen Refresh plus new fields",
    "description": "Byte/Clear | Sales/Ops: AIO Screen Refresh plus new fields",
    "priority": "High",
    "priorityLevel": "2 - High",
    "stackRank": 6,
    "status": "In Progress",
    "category": "Feature",
    "assignee": "Pam Miles",
    "createdDate": "2025-04-02",
    "workItemType": "Byte Request",
    "state": "In QA",
    "requestor": "Dave Herbst",
    "tags": [],
    "explanation": ""
  },
  {
    "id": "89297",
    "title": "Byte | Ops / Processing: Hardstop for delegated MI when non-delegated is required.",
    "description": "Byte | Ops / Processing: Hardstop for delegated MI when non-delegated is required.",
    "priority": "High",
    "priorityLevel": "2 - High",
    "stackRank": 7,
    "status": "In Progress",
    "category": "Feature",
    "assignee": "Renee Perrault",
    "createdDate": "2025-12-01",
    "workItemType": "User Story",
    "state": "BSA in Progress",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "explanation": ""
  },
  {
    "id": "58307",
    "title": "Byte | Closing: eNote & RON Eligibililty, Requested, Cancelled & Completed fields & logic",
    "description": "Byte | Closing: eNote & RON Eligibililty, Requested, Cancelled & Completed fields & logic",
    "priority": "High",
    "priorityLevel": "2 - High",
    "stackRank": 8,
    "status": "In Progress",
    "category": "Feature",
    "assignee": "Renee Perrault",
    "createdDate": "2025-03-18",
    "workItemType": "Byte Request",
    "state": "In QA",
    "requestor": "mbaetzel@cmgfi.com",
    "tags": [],
    "explanation": "Currently being tested per DocuTech meeting"
  },
  {
    "id": "91254",
    "title": "Byte / Doc Vendor | Compliance / Servicing / Post Closing: Bond First Payment Letters",
    "description": "Byte / Doc Vendor | Compliance / Servicing / Post Closing: Bond First Payment Letters",
    "priority": "High",
    "priorityLevel": "2 - High",
    "stackRank": 9,
    "status": "Blocked",
    "category": "Feature",
    "assignee": "Renee Perrault",
    "createdDate": "2025-12-23",
    "workItemType": "User Story",
    "state": "On Hold",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "explanation": "Waiting on Prod Dev research"
  },
  {
    "id": "92233",
    "title": "Byte | Ops / Underwriting: Need a new status dropdown on the conditions",
    "description": "Byte | Ops / Underwriting: Need a new status dropdown on the conditions",
    "priority": "High",
    "priorityLevel": "2 - High",
    "stackRank": 10,
    "status": "Blocked",
    "category": "Feature",
    "assignee": "Renee Perrault",
    "createdDate": "2026-01-07",
    "workItemType": "User Story",
    "state": "On Hold",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "explanation": "Requested from BytePro"
  },
  {
    "id": "91652",
    "title": "Byte | Ops Closing / Funding: Section G Fee Review",
    "description": "Byte | Ops Closing / Funding: Section G Fee Review",
    "priority": "High",
    "priorityLevel": "2 - High",
    "stackRank": 11,
    "status": "New",
    "category": "Feature",
    "assignee": "Aaron Cyr",
    "createdDate": "2025-12-30",
    "workItemType": "User Story",
    "state": "Prioritized Backlog",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "explanation": ""
  },
  {
    "id": "89718",
    "title": "Byte | Disclosures: Correct AIO fees for Franklin, TN branch when property is in NC.",
    "description": "Byte | Disclosures: Correct AIO fees for Franklin, TN branch when property is in NC.",
    "priority": "High",
    "priorityLevel": "2 - High",
    "stackRank": 12,
    "status": "New",
    "category": "Feature",
    "assignee": "Aaron Cyr",
    "createdDate": "2025-12-05",
    "workItemType": "User Story",
    "state": "Ready for Grooming",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "explanation": ""
  },
  {
    "id": "81505",
    "title": "Byte | Ops / Closing: SDHFA Fee Mapping Issue",
    "description": "Byte | Ops / Closing: SDHFA Fee Mapping Issue",
    "priority": "High",
    "priorityLevel": "2 - High",
    "stackRank": 13,
    "status": "In Progress",
    "category": "Feature",
    "assignee": "Aaron Cyr",
    "createdDate": "2025-10-13",
    "workItemType": "User Story",
    "state": "BSA in Progress",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "explanation": "Manual correction possible; low volume product"
  },
  {
    "id": "76231",
    "title": "Byte / SmartFees | Disclosures and Operations: NY Mortgage Tax Stamps Fee Mapping - Copy",
    "description": "Byte / SmartFees | Disclosures and Operations: NY Mortgage Tax Stamps Fee Mapping - Copy",
    "priority": "High",
    "priorityLevel": "2 - High",
    "stackRank": 14,
    "status": "In Progress",
    "category": "Feature",
    "assignee": "Aaron Cyr",
    "createdDate": "2025-08-25",
    "workItemType": "User Story",
    "state": "BSA in Progress",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "explanation": "Waiting for Compliance"
  },
  {
    "id": "90972",
    "title": "BYTE | Compliance: New York Byte Hardstop Updates",
    "description": "BYTE | Compliance: New York Byte Hardstop Updates",
    "priority": "High",
    "priorityLevel": "2 - High",
    "stackRank": 15,
    "status": "Blocked",
    "category": "Feature",
    "assignee": "Renee Perrault",
    "createdDate": "2025-12-18",
    "workItemType": "User Story",
    "state": "On Hold",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "explanation": "Waiting for Ops/Compliance"
  },
  {
    "id": "81479",
    "title": "Byte | Ops / Processing: Prepayment Penalty override",
    "description": "Byte | Ops / Processing: Prepayment Penalty override",
    "priority": "High",
    "priorityLevel": "2 - High",
    "stackRank": 16,
    "status": "Blocked",
    "category": "Feature",
    "assignee": "Renee Perrault",
    "createdDate": "2025-10-13",
    "workItemType": "User Story",
    "state": "On Hold",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "explanation": "Need to intiate request with Prod Dev"
  },
  {
    "id": "79086",
    "title": "Byte / CLEAR / Doc Vendor | Product / Operations: Need Assistance from Byte Team regarding upcoming CMG Bridge Loan Product - Copy",
    "description": "Byte / CLEAR / Doc Vendor | Product / Operations: Need Assistance from Byte Team regarding upcoming CMG Bridge Loan Product - Copy",
    "priority": "High",
    "priorityLevel": "2 - High",
    "stackRank": 17,
    "status": "Blocked",
    "category": "Feature",
    "assignee": "Renee Perrault",
    "createdDate": "2025-09-23",
    "workItemType": "Byte Request",
    "state": "On Hold",
    "requestor": "claudineb@cmgfi.com",
    "tags": [],
    "explanation": ""
  },
  // ========================================
  // 3 - MEDIUM (Stack Rank 18+)
  // ========================================
  {
    "id": "66212",
    "title": "Byte Dev | Underwriting: Need to update the 2nd Review-Exception screen in Byte to match our current Exception policy for Credit",
    "description": "Byte Dev | Underwriting: Need to update the 2nd Review-Exception screen in Byte to match our current Exception policy for Credit",
    "priority": "Medium",
    "priorityLevel": "3 - Medium",
    "stackRank": 18,
    "status": "Ready for Review",
    "category": "Feature",
    "assignee": "John Feldman",
    "createdDate": "2025-05-28",
    "workItemType": "Byte Request",
    "state": "Ready for Prod",
    "requestor": "kgriffin@cmghomeloans.com",
    "tags": [],
    "explanation": "Waiting for UW approval"
  },
  {
    "id": "69749",
    "title": "Byte Dev | Underwriting / Product: Need to lock down all Chase loan products so that any buydown cannot be borrower funded. - Copy",
    "description": "Byte Dev | Underwriting / Product: Need to lock down all Chase loan products so that any buydown cannot be borrower funded. - Copy",
    "priority": "Medium",
    "priorityLevel": "3 - Medium",
    "stackRank": 19,
    "status": "Ready for Review",
    "category": "Feature",
    "assignee": "Pam Miles",
    "createdDate": "2025-06-27",
    "workItemType": "Byte Request",
    "state": "Ready to Release with Clear",
    "requestor": "kgriffin@cmghomeloans.com",
    "tags": [],
    "explanation": ""
  },
  {
    "id": "76214",
    "title": "Byte / Clear | Underwriting: Requesting hard stop for income on the URLA for DSCR loans - Copy",
    "description": "Byte / Clear | Underwriting: Requesting hard stop for income on the URLA for DSCR loans - Copy",
    "priority": "Medium",
    "priorityLevel": "3 - Medium",
    "stackRank": 20,
    "status": "In Progress",
    "category": "Feature",
    "assignee": "John Feldman",
    "createdDate": "2025-08-25",
    "workItemType": "Byte Request",
    "state": "In Dev",
    "requestor": "kgriffin@cmghomeloans.com",
    "tags": [],
    "explanation": "Returned to dev due to unforseen impacts"
  },
  {
    "id": "78573",
    "title": "Byte | Corp Credit / Ops: Credit Vendor updates - Request to add mortgage only",
    "description": "Byte | Corp Credit / Ops: Credit Vendor updates - Request to add mortgage only",
    "priority": "Medium",
    "priorityLevel": "3 - Medium",
    "stackRank": 21,
    "status": "In Progress",
    "category": "Feature",
    "assignee": "Shannon Tavalero",
    "createdDate": "2025-09-17",
    "workItemType": "User Story",
    "state": "BSA in Progress",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "explanation": "Pending comm approval"
  },
  {
    "id": "91226",
    "title": "Byte | Ops / Closing / Post Closing: Form H8 and H9 - Hardstop",
    "description": "Byte | Ops / Closing / Post Closing: Form H8 and H9 - Hardstop",
    "priority": "Medium",
    "priorityLevel": "3 - Medium",
    "stackRank": 22,
    "status": "In Progress",
    "category": "Feature",
    "assignee": "Renee Perrault",
    "createdDate": "2025-12-23",
    "workItemType": "User Story",
    "state": "BSA in Progress",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "explanation": "Meeting Scheduled for 2/9"
  },
  {
    "id": "90878",
    "title": "BYTE / Clear | Ops Underwriting: Income Calc ID from Fannie Mae Income Calculator needs to be entered into Byte/DU",
    "description": "BYTE / Clear | Ops Underwriting: Income Calc ID from Fannie Mae Income Calculator needs to be entered into Byte/DU",
    "priority": "Medium",
    "priorityLevel": "3 - Medium",
    "stackRank": 23,
    "status": "In Progress",
    "category": "Feature",
    "assignee": "Shannon Tavalero",
    "createdDate": "2025-12-17",
    "workItemType": "User Story",
    "state": "BSA in Progress",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "explanation": "Pending testing with new version of Byte"
  },
  {
    "id": "79484",
    "title": "Byte / Clear | Sales / Ops: FNM DU for JV Solution - Copy",
    "description": "Byte / Clear | Sales / Ops: FNM DU for JV Solution - Copy",
    "priority": "Medium",
    "priorityLevel": "3 - Medium",
    "stackRank": 24,
    "status": "New",
    "category": "Feature",
    "assignee": "Unassigned",
    "createdDate": "2025-09-25",
    "workItemType": "Byte Request",
    "state": "New",
    "requestor": "tcrounse@cmgfi.com",
    "tags": [],
    "explanation": "Investor/Audit Request"
  },
  {
    "id": "56548",
    "title": "Byte/Clear | Sales/Product: Prepayment Penalty LOS Functionality - New PPP Screen",
    "description": "Byte/Clear | Sales/Product: Prepayment Penalty LOS Functionality - New PPP Screen",
    "priority": "Medium",
    "priorityLevel": "3 - Medium",
    "stackRank": 25,
    "status": "In Progress",
    "category": "Feature",
    "assignee": "Renee Perrault",
    "createdDate": "2025-03-03",
    "workItemType": "Byte Request",
    "state": "In QA",
    "requestor": "Amanda Lewis",
    "tags": [],
    "explanation": "Need for Post Closing"
  },
  {
    "id": "66076",
    "title": "Byte Dev | Disclosures: DHHL Attorney doc prep fee default add - $115.18",
    "description": "Byte Dev | Disclosures: DHHL Attorney doc prep fee default add - $115.18",
    "priority": "Medium",
    "priorityLevel": "3 - Medium",
    "stackRank": 26,
    "status": "In Progress",
    "category": "Feature",
    "assignee": "Aaron Cyr",
    "createdDate": "2025-05-27",
    "workItemType": "Byte Request",
    "state": "Gathering Requirements",
    "requestor": "nlindstrom@cmghomeloans.com",
    "tags": [],
    "explanation": "In flight"
  },
  {
    "id": "92379",
    "title": "BYTE | Ops Closing: Fee Lines for Settle In Program to flow to section H of CD",
    "description": "BYTE | Ops Closing: Fee Lines for Settle In Program to flow to section H of CD",
    "priority": "Medium",
    "priorityLevel": "3 - Medium",
    "stackRank": 27,
    "status": "New",
    "category": "Feature",
    "assignee": "Renee Perrault",
    "createdDate": "2026-01-09",
    "workItemType": "User Story",
    "state": "Prioritized Backlog",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "explanation": "Waiting for Ops"
  },
  {
    "id": "74762",
    "title": "Automation / BYTE / Docs Vendor | Servicing: Late Charges and NSFs",
    "description": "Automation / BYTE / Docs Vendor | Servicing: Late Charges and NSFs",
    "priority": "Medium",
    "priorityLevel": "3 - Medium",
    "stackRank": 28,
    "status": "New",
    "category": "Feature",
    "assignee": "Unassigned",
    "createdDate": "2025-08-12",
    "workItemType": "User Story",
    "state": "Prioritized Backlog",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "explanation": "Will need to create a script"
  },
  {
    "id": "81528",
    "title": "Byte / ValueLink | Ops / Closing: ValueLink Parcel ID Pushback",
    "description": "Byte / ValueLink | Ops / Closing: ValueLink Parcel ID Pushback",
    "priority": "Medium",
    "priorityLevel": "3 - Medium",
    "stackRank": 29,
    "status": "In Progress",
    "category": "Feature",
    "assignee": "Shannon Tavalero",
    "createdDate": "2025-10-14",
    "workItemType": "User Story",
    "state": "BSA in Progress",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "explanation": "In flight"
  },
  {
    "id": "86014",
    "title": "Byte / Doc Vendor | Product / Credit: FHA ARM – Byte Not Updating First Rate Payment Date Correctly",
    "description": "Byte / Doc Vendor | Product / Credit: FHA ARM – Byte Not Updating First Rate Payment Date Correctly",
    "priority": "Medium",
    "priorityLevel": "3 - Medium",
    "stackRank": 30,
    "status": "New",
    "category": "Feature",
    "assignee": "Renee Perrault",
    "createdDate": "2025-10-31",
    "workItemType": "User Story",
    "state": "Prioritized Backlog",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "explanation": ""
  },
  {
    "id": "87116",
    "title": "Byte / Docs | Post Closing / Ops / Underwriting: Updating URLA data in Byte",
    "description": "Byte / Docs | Post Closing / Ops / Underwriting: Updating URLA data in Byte",
    "priority": "Medium",
    "priorityLevel": "3 - Medium",
    "stackRank": 31,
    "status": "New",
    "category": "Feature",
    "assignee": "Renee Perrault",
    "createdDate": "2025-11-13",
    "workItemType": "User Story",
    "state": "Prioritized Backlog",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "explanation": "Waiting on Trade Team"
  },
  {
    "id": "89300",
    "title": "Byte | Ops / Underwriting / Processing: Prior to Purchase Hardstop",
    "description": "Byte | Ops / Underwriting / Processing: Prior to Purchase Hardstop",
    "priority": "Medium",
    "priorityLevel": "3 - Medium",
    "stackRank": 32,
    "status": "In Progress",
    "category": "Feature",
    "assignee": "Renee Perrault",
    "createdDate": "2025-12-01",
    "workItemType": "User Story",
    "state": "BSA in Progress",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "explanation": ""
  },
  {
    "id": "89333",
    "title": "Byte | Ops / Closing: Wiring Instructions Confirmation Date Macro to remove date after 7 business days & mirror the date on other Byte screens",
    "description": "Byte | Ops / Closing: Wiring Instructions Confirmation Date Macro to remove date after 7 business days & mirror the date on other Byte screens",
    "priority": "Medium",
    "priorityLevel": "3 - Medium",
    "stackRank": 33,
    "status": "New",
    "category": "Feature",
    "assignee": "Renee Perrault",
    "createdDate": "2025-12-01",
    "workItemType": "User Story",
    "state": "Prioritized Backlog",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "explanation": "Will need to create a bot"
  },
  {
    "id": "92476",
    "title": "Byte | Post Closing / Ops: Redisplay of Warehouse Bank Cardex Fields into new fields in Warehouse Info Screen",
    "description": "Byte | Post Closing / Ops: Redisplay of Warehouse Bank Cardex Fields into new fields in Warehouse Info Screen",
    "priority": "Medium",
    "priorityLevel": "3 - Medium",
    "stackRank": 34,
    "status": "In Progress",
    "category": "Feature",
    "assignee": "Renee Perrault",
    "createdDate": "2026-01-11",
    "workItemType": "User Story",
    "state": "BSA in Progress",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "explanation": ""
  },
  {
    "id": "89961",
    "title": "Byte | Secondary / Pricing: HELOC and 1st Lien Types",
    "description": "Byte | Secondary / Pricing: HELOC and 1st Lien Types",
    "priority": "Medium",
    "priorityLevel": "3 - Medium",
    "stackRank": 35,
    "status": "Blocked",
    "category": "Feature",
    "assignee": "Kelly Mattox",
    "createdDate": "2025-12-09",
    "workItemType": "User Story",
    "state": "On Hold",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "explanation": "Waiting for BytePro"
  },
  {
    "id": "22164",
    "title": "WV Refinance loans - Net Tangible Benefit screen and form incomplete - Need Hardstop",
    "description": "WV Refinance loans - Net Tangible Benefit screen and form incomplete - Need Hardstop",
    "priority": "Medium",
    "priorityLevel": "3 - Medium",
    "stackRank": 36,
    "status": "Ready for Review",
    "category": "Feature",
    "assignee": "John Feldman",
    "createdDate": "2024-04-22",
    "workItemType": "Byte Request",
    "state": "Ready to Release with Clear",
    "requestor": "Debbi Hundley",
    "tags": [],
    "explanation": "Ericka to follow up with Debbi Hundley to see if this could be restricted from self-disclosure"
  },
  {
    "id": "74328",
    "title": "Byte | Operations: Interested Party Contribution Calculation for CAP - Copy",
    "description": "Byte | Operations: Interested Party Contribution Calculation for CAP - Copy",
    "priority": "Medium",
    "priorityLevel": "3 - Medium",
    "stackRank": 37,
    "status": "In Progress",
    "category": "Feature",
    "assignee": "Pam Miles",
    "createdDate": "2025-08-08",
    "workItemType": "Byte Request",
    "state": "In QA",
    "requestor": "lforconi@cmgfi.com",
    "tags": [],
    "explanation": "CAP request"
  },
  {
    "id": "79335",
    "title": "Byte | App Support: Request to provide most current Email Notifications out of LOS - Copy",
    "description": "Byte | App Support: Request to provide most current Email Notifications out of LOS - Copy",
    "priority": "Medium",
    "priorityLevel": "3 - Medium",
    "stackRank": 38,
    "status": "In Progress",
    "category": "Feature",
    "assignee": "Emil Garcia",
    "createdDate": "2025-09-25",
    "workItemType": "Byte Request",
    "state": "In Dev",
    "requestor": "sierram@cmgfi.com",
    "tags": [],
    "explanation": ""
  },
  {
    "id": "77249",
    "title": "Byte | Processing: header of the URLA Borrower Screen that will display the REO/ Mortgages & HELOCS. - Copy",
    "description": "Byte | Processing: header of the URLA Borrower Screen that will display the REO/ Mortgages & HELOCS. - Copy",
    "priority": "Medium",
    "priorityLevel": "3 - Medium",
    "stackRank": 39,
    "status": "In Progress",
    "category": "Feature",
    "assignee": "Renee Perrault",
    "createdDate": "2025-09-04",
    "workItemType": "Byte Request",
    "state": "Gathering Requirements",
    "requestor": "rperrault@cmgfi.com/Jenn Houston",
    "tags": [],
    "explanation": ""
  },
  {
    "id": "84372",
    "title": "EX | Byte / Doc Vendor | Sales / Servicing / Ops / Compliance: Assumption Loans in Byte and Docs",
    "description": "EX | Byte / Doc Vendor | Sales / Servicing / Ops / Compliance: Assumption Loans in Byte and Docs",
    "priority": "Medium",
    "priorityLevel": "3 - Medium",
    "stackRank": 40,
    "status": "New",
    "category": "Feature",
    "assignee": "Renee Perrault",
    "createdDate": "2025-10-20",
    "workItemType": "User Story",
    "state": "Prioritized Backlog",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "explanation": ""
  },
  {
    "id": "72957",
    "title": "Byte | Ops / Disclosures: Open Section A \"Application Fee\" Line item for editable access by a Disclosure Coordinator persona",
    "description": "Byte | Ops / Disclosures: Open Section A \"Application Fee\" Line item for editable access by a Disclosure Coordinator persona",
    "priority": "Medium",
    "priorityLevel": "3 - Medium",
    "stackRank": 41,
    "status": "New",
    "category": "Feature",
    "assignee": "Aaron Cyr",
    "createdDate": "2025-07-30",
    "workItemType": "User Story",
    "state": "Prioritized Backlog",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "explanation": ""
  },
  {
    "id": "85773",
    "title": "Byte | Ops / Underwriting: Document Redisplay for Expiration Dates",
    "description": "Byte | Ops / Underwriting: Document Redisplay for Expiration Dates",
    "priority": "Medium",
    "priorityLevel": "3 - Medium",
    "stackRank": 42,
    "status": "New",
    "category": "Feature",
    "assignee": "Renee Perrault",
    "createdDate": "2025-10-29",
    "workItemType": "User Story",
    "state": "Prioritized Backlog",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "explanation": "Related to Important Dates Screen"
  },
  {
    "id": "90323",
    "title": "BYTE / Clear 1 | Sales: WHL Change of circumstance automation",
    "description": "BYTE / Clear 1 | Sales: WHL Change of circumstance automation",
    "priority": "Medium",
    "priorityLevel": "3 - Medium",
    "stackRank": 43,
    "status": "New",
    "category": "Feature",
    "assignee": "Kelly Mattox",
    "createdDate": "2025-12-14",
    "workItemType": "User Story",
    "state": "Prioritized Backlog",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "explanation": ""
  },
  {
    "id": "78632",
    "title": "Byte / Bundle Builder | Post Closing: AUS - DU - Add Support for DU Findings in PDF Format - Copy",
    "description": "Byte / Bundle Builder | Post Closing: AUS - DU - Add Support for DU Findings in PDF Format - Copy",
    "priority": "Medium",
    "priorityLevel": "3 - Medium",
    "stackRank": 44,
    "status": "New",
    "category": "Feature",
    "assignee": "Brian Carlon",
    "createdDate": "2025-09-17",
    "workItemType": "Byte Request",
    "state": "New",
    "requestor": "apaulsen@cmgfi.com",
    "tags": [],
    "explanation": "Waiting for BytePro"
  },
  {
    "id": "87832",
    "title": "Byte / Clear | Sales / Ops / Disclosures: Lender Paid Comp populating as Discount Points",
    "description": "Byte / Clear | Sales / Ops / Disclosures: Lender Paid Comp populating as Discount Points",
    "priority": "Medium",
    "priorityLevel": "3 - Medium",
    "stackRank": 45,
    "status": "New",
    "category": "Feature",
    "assignee": "Aaron Cyr",
    "createdDate": "2025-11-19",
    "workItemType": "User Story",
    "state": "Prioritized Backlog",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "explanation": ""
  },
  {
    "id": "90970",
    "title": "BYTE | Servicing / Product: - Simple Interest field (Byte Program Defaults) (Project)",
    "description": "BYTE | Servicing / Product: - Simple Interest field (Byte Program Defaults) (Project)",
    "priority": "Medium",
    "priorityLevel": "3 - Medium",
    "stackRank": 46,
    "status": "New",
    "category": "Feature",
    "assignee": "Unassigned",
    "createdDate": "2025-12-18",
    "workItemType": "User Story",
    "state": "Prioritized Backlog",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "explanation": ""
  },
  {
    "id": "21461",
    "title": "Gift Letter update request",
    "description": "Gift Letter update request",
    "priority": "Medium",
    "priorityLevel": "3 - Medium",
    "stackRank": 47,
    "status": "Ready for Review",
    "category": "Feature",
    "assignee": "John Feldman",
    "createdDate": "2024-04-08",
    "workItemType": "Byte Request",
    "state": "Ready to Release with Clear",
    "requestor": "Lissa Park",
    "tags": [],
    "explanation": "Waiting for Clear"
  },
  // ========================================
  // 4 - LOW (Stack Rank 48+)
  // ========================================
  {
    "id": "78917",
    "title": "Doc | Disclosures: URGENT LE DELIVERY DATE ISSUE",
    "description": "Doc | Disclosures: URGENT LE DELIVERY DATE ISSUE",
    "priority": "Low",
    "priorityLevel": "4 - Low",
    "stackRank": 48,
    "status": "New",
    "category": "Feature",
    "assignee": "Kelly Mattox",
    "createdDate": "2025-09-22",
    "workItemType": "User Story",
    "state": "Prioritized Backlog",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "explanation": ""
  },
  {
    "id": "89991",
    "title": "Doc Vendor | Ops / Closing: FHA Lead Base Paint Auto Condition",
    "description": "Doc Vendor | Ops / Closing: FHA Lead Base Paint Auto Condition",
    "priority": "Low",
    "priorityLevel": "4 - Low",
    "stackRank": 49,
    "status": "In Progress",
    "category": "Feature",
    "assignee": "Renee Perrault",
    "createdDate": "2025-12-09",
    "workItemType": "User Story",
    "state": "BSA in Progress",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "explanation": ""
  },
  {
    "id": "86228",
    "title": "Byte / Clear | Sales / Product / Secondary: .5-1 Buydown Option",
    "description": "Byte / Clear | Sales / Product / Secondary: .5-1 Buydown Option",
    "priority": "Low",
    "priorityLevel": "4 - Low",
    "stackRank": 50,
    "status": "New",
    "category": "Feature",
    "assignee": "Renee Perrault",
    "createdDate": "2025-11-04",
    "workItemType": "User Story",
    "state": "Prioritized Backlog",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "explanation": "Waiting for 26.1 - Q2"
  },
  {
    "id": "74085",
    "title": "Byte / ComplianceEase | Disclosures / Closing: ComplianceAnalyzer BytePro Updates",
    "description": "Byte / ComplianceEase | Disclosures / Closing: ComplianceAnalyzer BytePro Updates",
    "priority": "Low",
    "priorityLevel": "4 - Low",
    "stackRank": 51,
    "status": "New",
    "category": "Feature",
    "assignee": "Kelly Mattox",
    "createdDate": "2025-08-07",
    "workItemType": "User Story",
    "state": "Prioritized Backlog",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "explanation": ""
  },
  {
    "id": "61917",
    "title": "Byte | Underwriting: Add Assignment for VP Underwriting",
    "description": "Byte | Underwriting: Add Assignment for VP Underwriting",
    "priority": "Low",
    "priorityLevel": "4 - Low",
    "stackRank": 52,
    "status": "In Progress",
    "category": "Feature",
    "assignee": "Aaron Cyr",
    "createdDate": "2025-04-17",
    "workItemType": "Byte Request",
    "state": "In Dev",
    "requestor": "Colleen Schofield",
    "tags": [],
    "explanation": "Waiting for UW"
  },
  {
    "id": "78426",
    "title": "Byte | Product / Closing / Post Closing: Non-HFA DPA Programs - Auto-Populate Data into Funding Screen",
    "description": "Byte | Product / Closing / Post Closing: Non-HFA DPA Programs - Auto-Populate Data into Funding Screen",
    "priority": "Low",
    "priorityLevel": "4 - Low",
    "stackRank": 53,
    "status": "Blocked",
    "category": "Feature",
    "assignee": "Renee Perrault",
    "createdDate": "2025-09-15",
    "workItemType": "User Story",
    "state": "On Hold",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "explanation": ""
  },
  {
    "id": "81621",
    "title": "Byte / Clear Docs | Sales: Daily Summary for activity in the loan (SC notes)",
    "description": "Byte / Clear Docs | Sales: Daily Summary for activity in the loan (SC notes)",
    "priority": "Low",
    "priorityLevel": "4 - Low",
    "stackRank": 54,
    "status": "New",
    "category": "Feature",
    "assignee": "Unassigned",
    "createdDate": "2025-10-14",
    "workItemType": "User Story",
    "state": "Prioritized Backlog",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "explanation": ""
  },
  {
    "id": "65701",
    "title": "Byte | Clear: Secondary Pricing: Request to re-address the COC/Points increase tech side of workflow - From 25.1 Release",
    "description": "Byte | Clear: Secondary Pricing: Request to re-address the COC/Points increase tech side of workflow - From 25.1 Release",
    "priority": "Low",
    "priorityLevel": "4 - Low",
    "stackRank": 55,
    "status": "In Progress",
    "category": "Feature",
    "assignee": "Aaron Cyr",
    "createdDate": "2025-05-23",
    "workItemType": "User Story",
    "state": "BSA in Progress",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "explanation": ""
  },
  {
    "id": "93150",
    "title": "Byte | Sales / Ops: Essent MI Integration - 401 Unauthorized Errors for 3+ Months",
    "description": "Byte | Sales / Ops: Essent MI Integration - 401 Unauthorized Errors for 3+ Months",
    "priority": "Low",
    "priorityLevel": "4 - Low",
    "stackRank": 56,
    "status": "New",
    "category": "Feature",
    "assignee": "Kelly Mattox",
    "createdDate": "2026-01-20",
    "workItemType": "User Story",
    "state": "New",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "explanation": "Pending feedback from Engineering"
  },
  // ========================================
  // 5 - LOWEST (Stack Rank 57+)
  // ========================================
  {
    "id": "89658",
    "title": "BYTE / Clear | Sales: credit report after file submission - Copy",
    "description": "BYTE / Clear | Sales: credit report after file submission - Copy",
    "priority": "Low",
    "priorityLevel": "5 - Lowest",
    "stackRank": 57,
    "status": "New",
    "category": "Feature",
    "assignee": "Unassigned",
    "createdDate": "2025-12-04",
    "workItemType": "User Story",
    "state": "Prioritized Backlog",
    "requestor": "Product Masters\\BYTE\\BYTE Platform",
    "tags": [],
    "explanation": "Waiting for Sales"
  },
];
